### ISSUE TITLE
Installation throws a PermissionError on Windows

### ISSUE THREAD

**Issue by aburnettnf** [yhat/pandasql#48]
Hi there!

I noticed that running the indicated installation command:

`> pip install -U git+https://github.com/aplavin/pandasql.git`

...resulted in a PermissionError:

> PermissionError: [WinError 5] Access is denied: 'C:\\Users\\aburnett\\AppData\\Local\\Temp\\pip-k5bywsvx-uninstall\\python\\python35\\lib\\site-packages\\pandas\\algos.cp35-win_amd64.pyd'

Actually I received the permission error the first time, reran the same command a second time, received the error a second time, ran the command a third time, received a similar error, and reran the command a fourth time before installation completed successfully. It seemed that it was throwing PermissionErrors for various components in the /lib directory.

**Comment by glamp** [comment]
I'm not sure what fork you installed but it's not supported (at least here). 

Use 'pip install pandasql' instead.

**Comment by aburnettnf** [comment]
@glamp Thank you, Greg!
