### ISSUE TITLE
LEFT OUTER JOIN resolves to LEFT JOIN

### ISSUE THREAD

**Issue by dreyco676** [yhat/pandasql#50]
Left outer join should provide only the data that does not have a match to the right table. Instead this seems to resolve to a left join.

```
import pandas as pd
from pandasql import PandaSQL

df_a = pd.DataFrame({'test': pd.Series([1., 2., 3., 4.])})
df_b = pd.DataFrame({'test': pd.Series([1., 2., 3.])})

pdsql = PandaSQL()
joined_df = pdsql("SELECT a.* FROM df_a a LEFT OUTER JOIN df_b b on a.test = b.test")
print(joined_df)
```

Outputs:

```
   test
0   1.0
1   2.0
2   3.0
3   4.0
```

Expected Output:
```
   test
3   4.0
```

**Comment by YurZ** [comment]
@dreyco676 In SQL 'LEFT OUTER JOIN' and 'LEFT JOIN' is the same command, it's just 'OUTER' word often gets omitted.

**Comment by dreyco676** [comment]
You seem to be confusing INNER and OUTER. INNER JOIN will resolve to JOIN. Likewise LEFT INNER JOIN would resolve to LEFT JOIN.

LEFT OUTER JOIN is illustrated on this page and is not equivalent to LEFT JOIN:
http://blog.codinghorror.com/a-visual-explanation-of-sql-joins/

**Comment by dreyco676** [comment]
Crap you're right. According to this I forgot the WHERE clause.

http://blog.codinghorror.com/a-visual-explanation-of-sql-joins/
