### ISSUE TITLE
window Function - Row_Number not working

### ISSUE THREAD

**Issue by saketdabi1385** [yhat/pandasql#77]
Hi I am truing to use window functions but it seems they are not supported ? on checking i found out that sqllite recently enabled them. Do you think you can include them as well.

**Comment by stonebig** [comment]
in theory nothing is impossible

![image](https://user-images.githubusercontent.com/4312421/63539380-3c1f0c00-c51a-11e9-93b4-348e866de54e.png)

![image](https://user-images.githubusercontent.com/4312421/63540052-a71d1280-c51b-11e9-9438-27548eea047b.png)

**Comment by saketdabi1385** [comment]
still running into Execution failed on sql 'select row_number() over
(partition by asin)': near "(": syntax error while doing this

import pandas as pd
from pandasql import sqldf
from baresql import  baresql
df = pd.read_csv(r'C:\Automation\Simulator\file.csv', index_col=0)
bsql = baresql.baresql(keep_log=True)
bsqldf = lambda q: bsql.df(q, dict(globals(),**locals()))

print('data read')
query = "select row_number() over (partition by date)"

query_result = bsqldf(query)

print(query_result.head())

Regards
*Saket Dabi*

**Comment by saketdabi1385** [comment]
query = """select row_number() over (partition by date) from df;""" same error

**Comment by stonebig** [comment]
query = "select row_number() over (partition by date) from df$$"
or
query = "select row_number() over (order by date) from df$$"

may be better ? never tried with a date format though

**Comment by stonebig** [comment]
![image](https://user-images.githubusercontent.com/4312421/63547023-7e9d1480-c52b-11e9-944a-84108616c930.png)

**Comment by saketdabi1385** [comment]
even this simple aint working .. its shocking

query = """select row_number() over ()  as rn from dff$$;"""

# query_result = bsqldf(query)

q = bsqldf(query)

Regards
*Saket Dabi*

**Comment by stonebig** [comment]
maybe try bsqldf("select sqlite_version()". only Python-3.7.4 has a fresh enough sqlite motor

**Comment by saketdabi1385** [comment]
its 3.21.0

**Comment by stonebig** [comment]
so now, you know the problem

**Comment by saketdabi1385** [comment]
what did i miss ? version ?which version ?

**Comment by stonebig** [comment]
https://www.sqlite.org/releaselog/3_25_0.html

**Comment by stonebig** [comment]
https://bugs.python.org/issue35360

**Comment by saketdabi1385** [comment]
i did download the 3.25 version but how can i upgrade the package itself
for it to use 3.25 instead of 3.21

Regards
*Saket Dabi*

**Comment by stonebig** [comment]
Replace the sqlite3.dll. see https://www.google.com/amp/s/dfir.blog/upgrading-pythons-sqlite/amp/

**Comment by saketdabi1385** [comment]
done - works ..much thanks

**Comment by stonebig** [comment]
You may close the issue, if you are satisfied.

**Comment by saketdabi1385** [comment]
resolved
